# Firebase Configuration (required for authentication and database)
NEXT_PUBLIC_FIREBASE_API_KEY=your_api_key_here
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=your_auth_domain_here
NEXT_PUBLIC_FIREBASE_PROJECT_ID=your_project_id_here
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=your_storage_bucket_here
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=your_sender_id_here
NEXT_PUBLIC_FIREBASE_APP_ID=your_app_id_here

# Webhook URLs (required for booking logic)
NEXT_PUBLIC_WEBHOOK_URL_AVAILABLE_TIME_SLOTS=your_availability_webhook_url_here
NEXT_PUBLIC_WEBHOOK_URL_BOOKING_CONFIRMATION=your_confirmation_webhook_url_here

# Genkit AI Configuration (required for AI features)
GEMINI_API_KEY=your_gemini_api_key_here